import { useState, useRef } from "react";
import { QRCodeSVG } from "qrcode.react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Download, Link, Copy, Check, QrCode, FileText } from "lucide-react";
import { toast } from "@/hooks/use-toast";
import jsPDF from "jspdf";

interface QRGeneratorProps {
  onGenerate?: (url: string, id: string) => void;
}

export function QRGenerator({ onGenerate }: QRGeneratorProps) {
  const [url, setUrl] = useState("");
  const [generatedQR, setGeneratedQR] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const qrRef = useRef<HTMLDivElement>(null);

  const handleGenerate = () => {
    if (!url.trim()) {
      toast({
        title: "URL Required",
        description: "Please enter a valid URL to generate a QR code.",
        variant: "destructive",
      });
      return;
    }

    let processedUrl = url.trim();
    if (!processedUrl.startsWith("http://") && !processedUrl.startsWith("https://")) {
      processedUrl = `https://${processedUrl}`;
    }

    setGeneratedQR(processedUrl);
    const qrId = `qr_${Date.now()}`;
    onGenerate?.(processedUrl, qrId);
    
    toast({
      title: "QR Code Generated!",
      description: "Your QR code is ready to download.",
    });
  };

  const getQRCanvas = (): Promise<HTMLCanvasElement | null> => {
    return new Promise((resolve) => {
      if (!qrRef.current || !generatedQR) {
        resolve(null);
        return;
      }

      const svg = qrRef.current.querySelector("svg");
      if (!svg) {
        resolve(null);
        return;
      }

      const canvas = document.createElement("canvas");
      const ctx = canvas.getContext("2d");
      const data = new XMLSerializer().serializeToString(svg);
      const img = new Image();
      
      canvas.width = 512;
      canvas.height = 512;

      img.onload = () => {
        ctx?.drawImage(img, 0, 0, 512, 512);
        resolve(canvas);
      };

      img.onerror = () => resolve(null);
      img.src = `data:image/svg+xml;base64,${btoa(unescape(encodeURIComponent(data)))}`;
    });
  };

  const handleDownloadPNG = async () => {
    const canvas = await getQRCanvas();
    if (!canvas) return;

    const pngUrl = canvas.toDataURL("image/png");
    const downloadLink = document.createElement("a");
    downloadLink.href = pngUrl;
    downloadLink.download = `qr-code-${Date.now()}.png`;
    document.body.appendChild(downloadLink);
    downloadLink.click();
    document.body.removeChild(downloadLink);

    toast({
      title: "Downloaded!",
      description: "QR code saved as PNG.",
    });
  };

  const handleDownloadPDF = async () => {
    const canvas = await getQRCanvas();
    if (!canvas || !generatedQR) return;

    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    const pageWidth = pdf.internal.pageSize.getWidth();
    const qrSize = 80;
    const xPos = (pageWidth - qrSize) / 2;

    // Add title
    pdf.setFontSize(24);
    pdf.setFont("helvetica", "bold");
    pdf.text("QR Code", pageWidth / 2, 30, { align: "center" });

    // Add QR code
    const imgData = canvas.toDataURL("image/png");
    pdf.addImage(imgData, "PNG", xPos, 50, qrSize, qrSize);

    // Add URL below QR code
    pdf.setFontSize(10);
    pdf.setFont("helvetica", "normal");
    const urlText = generatedQR.length > 60 ? generatedQR.substring(0, 60) + "..." : generatedQR;
    pdf.text(urlText, pageWidth / 2, 145, { align: "center" });

    // Add footer
    pdf.setFontSize(8);
    pdf.setTextColor(128, 128, 128);
    pdf.text("Generated by QRTrack", pageWidth / 2, 280, { align: "center" });

    pdf.save(`qr-code-${Date.now()}.pdf`);

    toast({
      title: "Downloaded!",
      description: "QR code saved as PDF.",
    });
  };

  const handleCopyUrl = async () => {
    if (!generatedQR) return;
    
    await navigator.clipboard.writeText(generatedQR);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    
    toast({
      title: "Copied!",
      description: "URL copied to clipboard.",
    });
  };

  return (
    <div className="w-full max-w-xl mx-auto" id="generate">
      <div className="glass-card rounded-2xl p-4 sm:p-6 md:p-8 animate-fade-in">
        <div className="space-y-4 sm:space-y-6">
          <div className="space-y-2">
            <Label htmlFor="url" className="text-sm font-medium text-foreground/80">
              Enter URL
            </Label>
            <div className="relative">
              <Link className="absolute left-3 sm:left-4 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
              <Input
                id="url"
                type="url"
                placeholder="https://example.com"
                value={url}
                onChange={(e) => setUrl(e.target.value)}
                onKeyDown={(e) => e.key === "Enter" && handleGenerate()}
                className="pl-10 sm:pl-11 h-11 sm:h-12 bg-background/50 border-border/50 focus:border-primary transition-colors font-mono text-sm"
              />
            </div>
          </div>

          <Button
            onClick={handleGenerate}
            variant="gradient"
            className="w-full h-11 sm:h-12"
          >
            <QrCode className="mr-2 h-5 w-5" />
            Generate QR Code
          </Button>
        </div>

        {generatedQR && (
          <div className="mt-6 sm:mt-8 pt-6 sm:pt-8 border-t border-border/50 animate-scale-in">
            <div className="flex flex-col items-center gap-4 sm:gap-6">
              <div 
                ref={qrRef}
                className="p-4 sm:p-6 bg-background rounded-xl border border-border/30 animate-pulse-glow"
              >
                <QRCodeSVG
                  value={generatedQR}
                  size={160}
                  level="H"
                  includeMargin={false}
                  bgColor="transparent"
                  fgColor="currentColor"
                  className="text-foreground sm:w-[200px] sm:h-[200px]"
                />
              </div>

              <p className="text-xs sm:text-sm text-muted-foreground font-mono truncate max-w-full px-2 sm:px-4">
                {generatedQR}
              </p>

              <div className="flex flex-col sm:flex-row gap-2 sm:gap-3 w-full">
                <Button
                  onClick={handleCopyUrl}
                  variant="secondary"
                  className="flex-1 h-10 sm:h-11 bg-secondary hover:bg-secondary/80 transition-all duration-200 text-sm"
                >
                  {copied ? (
                    <Check className="mr-2 h-4 w-4 text-green-500" />
                  ) : (
                    <Copy className="mr-2 h-4 w-4" />
                  )}
                  {copied ? "Copied!" : "Copy URL"}
                </Button>
                <Button
                  onClick={handleDownloadPNG}
                  variant="gradient"
                  className="flex-1 h-10 sm:h-11 text-sm"
                >
                  <Download className="mr-2 h-4 w-4" />
                  PNG
                </Button>
                <Button
                  onClick={handleDownloadPDF}
                  variant="gradient"
                  className="flex-1 h-10 sm:h-11 text-sm"
                >
                  <FileText className="mr-2 h-4 w-4" />
                  PDF
                </Button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
